apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: splight-backup-service-account
data:
  splight-backup.json: {{ .Values.splightBackupServiceAccount }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: splight-backup
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: splight-backup
              image: jacquev6/splight:{{ .Values.version }}.backup
              env:
                - name: SPLIGHT_MONGODB_URL
                  value: "mongodb://splight-mongo:27017/"
                - name: SPLIGHT_PROJECT_ID
                  value: jacquev6-0001
              volumeMounts:
                - name: service-accounts
                  mountPath: /service-accounts
                  readOnly: true
              resources:
                requests:
                  cpu: 10m
          volumes:
            - name: service-accounts
              secret:
                secretName: splight-backup-service-account
          restartPolicy: Never
{{ if .Values.restore }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: splight-restore
spec:
  template:
    spec:
      containers:
        - name: splight-restore
          image: jacquev6/splight:{{ .Values.version }}.backup
          args:
            - restore
            - {{ .Values.restore }}
          env:
            - name: SPLIGHT_MONGODB_URL
              value: "mongodb://splight-mongo:27017/"
            - name: SPLIGHT_PROJECT_ID
              value: jacquev6-0001
          volumeMounts:
            - name: service-accounts
              mountPath: /service-accounts
              readOnly: true
          resources:
            requests:
              cpu: 10m
      volumes:
        - name: service-accounts
          secret:
            secretName: splight-backup-service-account
      restartPolicy: Never
{{ end }}
