apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ .Values.baseName }}-backup-service-account
data:
  splight-backup.json: {{ .Values.splightBackupServiceAccount }}
{{ if .Values.periodicalBackups }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.baseName }}-periodical-backup
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Values.baseName }}-periodical-backup
              image: jacquev6/splight:{{ .Values.version }}.backup
              args:
                - backup
              env:
                - name: SPLIGHT_MONGODB_URL
                  value: "mongodb://{{ .Values.baseName }}-mongo:27017/"
                - name: SPLIGHT_PROJECT_ID
                  value: jacquev6-0001
                - name: SPLIGHT_INSTANCE_SLUG
                  value: {{ .Values.periodicalBackups }}
              volumeMounts:
                - name: service-accounts
                  mountPath: /service-accounts
                  readOnly: true
              resources:
                requests:
                  cpu: 10m
          volumes:
            - name: service-accounts
              secret:
                secretName: {{ .Values.baseName }}-backup-service-account
          restartPolicy: Never
{{ end }}
{{ if .Values.periodicalRestores }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.baseName }}-periodical-restore
spec:
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Values.baseName }}-periodical-restore
              image: jacquev6/splight:{{ .Values.version }}.backup
              args:
                - restore-latest
                - {{ .Values.periodicalRestores }}
              env:
                - name: SPLIGHT_MONGODB_URL
                  value: "mongodb://{{ .Values.baseName }}-mongo:27017/"
                - name: SPLIGHT_PROJECT_ID
                  value: jacquev6-0001
              volumeMounts:
                - name: service-accounts
                  mountPath: /service-accounts
                  readOnly: true
              resources:
                requests:
                  cpu: 10m
          volumes:
            - name: service-accounts
              secret:
                secretName: {{ .Values.baseName }}-backup-service-account
          restartPolicy: Never
{{ end }}
{{ if .Values.periodicalTestDataRestores }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.baseName }}-periodical-test-data-restore
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Values.baseName }}-periodical-test-data-restore
              image: jacquev6/splight:{{ .Values.version }}.test-data
              env:
                - name: SPLIGHT_MONGODB_URL
                  value: "mongodb://{{ .Values.baseName }}-mongo:27017/"
                - name: SPLIGHT_API_URL
                  value: "http://{{ .Values.baseName }}-api/graphql"
              resources:
                requests:
                  cpu: 10m
          restartPolicy: Never
{{ end }}
{{ if .Values.restoreOnce }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.baseName }}-restore
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.baseName }}-restore
          image: jacquev6/splight:{{ .Values.version }}.backup
          args:
            - restore
            - {{ .Values.restoreOnce }}
          env:
            - name: SPLIGHT_MONGODB_URL
              value: "mongodb://{{ .Values.baseName }}-mongo:27017/"
            - name: SPLIGHT_PROJECT_ID
              value: jacquev6-0001
          volumeMounts:
            - name: service-accounts
              mountPath: /service-accounts
              readOnly: true
          resources:
            requests:
              cpu: 10m
      volumes:
        - name: service-accounts
          secret:
            secretName: {{ .Values.baseName }}-backup-service-account
      restartPolicy: Never
{{ end }}
