kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.baseName }}-mongo
spec:
  selector:
    matchLabels:
      app: {{ .Values.baseName }}-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.baseName }}-mongo
    spec:
      containers:
        - name: {{ .Values.baseName }}-mongo
          image: mongo:3.6.9
          volumeMounts:
            - mountPath: /data/db
              name: {{ .Values.baseName }}-mongo
          resources:
            requests:
              cpu: 10m
      volumes:
        - name: {{ .Values.baseName }}-mongo
          gcePersistentDisk:
            pdName: {{ .Values.mongoPersistentDiskName }}
            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.baseName }}-mongo
spec:
  selector:
    app: {{ .Values.baseName }}-mongo
  ports:
    - port: 27017
