#!/bin/bash

set -o errexit

INFRASTRUCTURE_TOOLS_TAG=20190401-121342

NAME=infrastructure-tools-$INFRASTRUCTURE_TOOLS_TAG

if ! docker ps | grep $NAME >/dev/null
then
  docker run \
    --rm --name $NAME --detach \
    --mount type=bind,src=$PWD,dst=/infrastructure \
    jacquev6/infrastructure-tools:$INFRASTRUCTURE_TOOLS_TAG \
    bash -c "tail -f /dev/null" \
  >/dev/null
fi

TTY_OPTION=""

if [ -t 0 ]
then
  TTY_OPTION="--tty"
fi

docker exec --interactive $TTY_OPTION $NAME /infra "$@"
