#!/bin/bash

set -o errexit

INFRASTRUCTURE_TOOLS_TAG=20200312-093620

# Clean-up:
# docker image ls jacquev6/infrastructure-tools --format "{{.Repository}}:{{.Tag}}" | grep -v $INFRASTRUCTURE_TOOLS_TAG | xargs docker image rm
# docker image ls infrastructure-tools-builder --format "{{.Repository}}:{{.Tag}}" | grep -v $INFRASTRUCTURE_TOOLS_TAG | xargs docker image rm

NAME=infrastructure-tools-main-$INFRASTRUCTURE_TOOLS_TAG

if [ -z $(docker ps --quiet --filter name=$NAME) ]
then
  docker ps --quiet --filter name=infrastructure-tools- | xargs docker kill

  docker run \
    --rm --name $NAME --detach \
    --mount type=bind,src=$PWD,dst=/infrastructure \
    --mount type=bind,src=$HOME/.ssh,dst=/root/.ssh \
    jacquev6/infrastructure-tools:main-$INFRASTRUCTURE_TOOLS_TAG \
    bash -c "tail -f /dev/null" \
  >/dev/null
fi

TTY_OPTION=""

if [ -t 0 -a -t 1 -a -t 2 ]
then
  TTY_OPTION="--tty"
fi

docker exec --interactive $TTY_OPTION $NAME /infra.py "$@"
