#!/bin/bash

set -o errexit

INFRASTRUCTURE_TOOLS_TAG=20190222-080356

TTY_OPTION=""

if [ -t 0 ]
then
  TTY_OPTION="--tty"
fi

docker run --interactive $TTY_OPTION \
  --mount type=bind,src=$PWD/sources,dst=/sources \
  --mount type=bind,src=$HOME/.ssh,dst=/ssh,readonly \
  --env INFRA_UID=$(id -u) --env INFRA_GID=$(id -g) \
  jacquev6/infrastructure-tools:$INFRASTRUCTURE_TOOLS_TAG \
  -- "$@"
