apiVersion: apps/v1
kind: Deployment
metadata:
  name: draw-turks-head-demo
spec:
  selector:
    matchLabels:
      app: draw-turks-head-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: draw-turks-head-demo
    spec:
      containers:
        - name: draw-turks-head-demo
          image: jacquev6/draw-turks-head-demo:20190222-160624
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
---
apiVersion: v1
kind: Service
metadata:
  name: draw-turks-head-demo
spec:
  type: NodePort
  selector:
    app: draw-turks-head-demo
  ports:
    - port: 80
