apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fanout
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.fanoutName }}
    # Limit: 10 certificates (https://cloud.google.com/load-balancing/docs/ssl-certificates#ssl-certificate-limits)
    # Check certificates are applied: https://serverfault.com/a/661982/221556
    ingress.gcp.kubernetes.io/pre-shared-cert: "{{ .Values.preSharedCertificates }}"
spec:
  # Current quota: 15 backends (https://console.cloud.google.com/iam-admin/quotas?project=jacquev6-0001)
  backend:
    serviceName: fanout
    servicePort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fanout
data:
  haproxy.cfg: |
    defaults
      mode http
      timeout connect 5000
      timeout client 50000
      timeout server 50000
    frontend fanout
      bind *:80
      # VJNet
      acl is_www_vjnet hdr(host) www.vincent-jacques.net
      redirect location https://vincent-jacques.net/ code 301 if is_www_vjnet
      acl is_draw_turks_head_demo path /turkshead
      acl is_dyn_vjnet hdr(host) dyn.vincent-jacques.net
      use_backend draw_turks_head_demo if is_dyn_vjnet is_draw_turks_head_demo
      # # Splight pre-production
      # acl is_splight_preprod_preview url_beg /preview
      # acl is_splight_preprod_admin hdr(host) admin-preprod.splight.fr
      # acl is_splight_preprod_api hdr(host) api-preprod.splight.fr
      # acl is_splight_preprod_public hdr(host) preprod.splight.fr
      # use_backend splight_preprod_preview if is_splight_preprod_admin is_splight_preprod_preview
      # use_backend splight_preprod_admin if is_splight_preprod_admin
      # use_backend splight_preprod_api if is_splight_preprod_api
      # use_backend splight_preprod_public if is_splight_preprod_public
      # # Splight production
      # acl is_splight_prod_preview url_beg /preview
      # acl is_splight_prod_admin hdr(host) admin.splight.fr
      # acl is_splight_prod_api hdr(host) api.splight.fr
      # # @todo Change to "splight.fr" when we move out of GitHub Pages
      # acl is_splight_prod_public hdr(host) prod.splight.fr
      # use_backend splight_prod_preview if is_splight_prod_admin is_splight_prod_preview
      # use_backend splight_prod_admin if is_splight_prod_admin
      # use_backend splight_prod_api if is_splight_prod_api
      # use_backend splight_prod_public if is_splight_prod_public
      # Splight demonstration
      acl is_splight_demo_preview url_beg /preview
      acl is_splight_demo_admin hdr(host) splight-demo-admin.vincent-jacques.net
      acl is_splight_demo_api hdr(host) splight-demo-api.vincent-jacques.net
      acl is_splight_demo_public hdr(host) splight-demo.vincent-jacques.net
      use_backend splight_demo_preview if is_splight_demo_admin is_splight_demo_preview
      use_backend splight_demo_admin if is_splight_demo_admin
      use_backend splight_demo_api if is_splight_demo_api
      use_backend splight_demo_public if is_splight_demo_public
      # Default backend must respond 200 on / for health checks from load balancer
      # @todo Could we respond with 200 directly from haproxy, and remove always_200?
      default_backend always_200
    backend draw_turks_head_demo
      server draw_turks_head_demo draw-turks-head-demo
    # backend splight_preprod_public
    #   server splight_preprod_public splight-preprod-public
    # backend splight_preprod_api
    #   server splight_preprod_api splight-preprod-api
    # backend splight_preprod_admin
    #   server splight_preprod_admin splight-preprod-admin
    # backend splight_preprod_preview
    #   server splight_preprod_preview splight-preprod-preview
    # backend splight_prod_public
    #   server splight_prod_public splight-prod-public
    # backend splight_prod_api
    #   server splight_prod_api splight-prod-api
    # backend splight_prod_admin
    #   server splight_prod_admin splight-prod-admin
    # backend splight_prod_preview
    #   server splight_prod_preview splight-prod-preview
    backend splight_demo_public
      server splight_demo_public splight-demo-public
    backend splight_demo_api
      server splight_demo_api splight-demo-api
    backend splight_demo_admin
      server splight_demo_admin splight-demo-admin
    backend splight_demo_preview
      server splight_demo_preview splight-demo-preview
    backend always_200
      server always_200 always-200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fanout
  annotations:
    configmap.reloader.stakater.com/reload: "fanout"
spec:
  selector:
    matchLabels:
      app: fanout
  replicas: 2
  template:
    metadata:
      labels:
        app: fanout
    spec:
      containers:
        - name: fanout
          image: haproxy:1.9.4-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
          volumeMounts:
            - name: etc-haproxy
              mountPath: /usr/local/etc/haproxy
      volumes:
        - name: etc-haproxy
          configMap:
            name: fanout
---
apiVersion: v1
kind: Service
metadata:
  name: fanout
spec:
  type: NodePort
  selector:
    app: fanout
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: always-200
spec:
  selector:
    matchLabels:
      app: always-200
  replicas: 2
  template:
    metadata:
      labels:
        app: always-200
    spec:
      containers:
        - name: always-200
          image: nginx:1.15
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
---
apiVersion: v1
kind: Service
metadata:
  name: always-200
spec:
  type: NodePort
  selector:
    app: always-200
  ports:
    - port: 80
