apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.fanoutName }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.fanoutName }}
    # Limit: 10 certificates (https://cloud.google.com/load-balancing/docs/ssl-certificates#ssl-certificate-limits)
    # Check certificates are applied: https://serverfault.com/a/661982/221556
    ingress.gcp.kubernetes.io/pre-shared-cert: "{{ .Values.preSharedCertificates }}"
spec:
  # Current quota: 15 backends (https://console.cloud.google.com/iam-admin/quotas?project=jacquev6-0001)
  rules:
    - host: dyn.vincent-jacques.net
      http:
        paths:
          - path: /turkshead
            backend:
              serviceName: draw-turks-head-demo
              servicePort: 80

    - host: preprod.splight.fr
      http:
        paths:
          - backend:
              serviceName: splight-preprod-public
              servicePort: 80
    - host: admin-preprod.splight.fr
      http:
        paths:
          - backend:
              serviceName: splight-preprod-admin
              servicePort: 80
          - path: /preview/*
            backend:
              serviceName: splight-preprod-preview
              servicePort: 80
          - path: /preview
            backend:
              serviceName: splight-preprod-preview
              servicePort: 80
    - host: api-preprod.splight.fr
      http:
        paths:
          - backend:
              serviceName: splight-preprod-api
              servicePort: 80

    - host: prod.splight.fr  # @todo Change to "splight.fr" when we move out of GitHub Pages
      http:
        paths:
          - path: /*
            backend:
              serviceName: splight-prod-public
              servicePort: 80
    - host: admin.splight.fr
      http:
        paths:
          - path: /*
            backend:
              serviceName: splight-prod-admin
              servicePort: 80
          - path: /preview/*
            backend:
              serviceName: splight-prod-preview
              servicePort: 80
          - path: /preview
            backend:
              serviceName: splight-prod-preview
              servicePort: 80
    - host: api.splight.fr
      http:
        paths:
          - path: /graphql
            backend:
              serviceName: splight-prod-api
              servicePort: 80
