- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Get v-doorman's SSH key"
      command: "ssh-keyscan 192.168.1.102"
      register: keys
    - name: "Store v-doorman's SSH key"
      lineinfile:
        dest: ~/.ssh/known_hosts
        line: "{{ item }}"
      with_items: "{{ keys.stdout_lines }}"
    - name: "Get v-node-1's SSH key"
      command: "ssh-keyscan 10.20.30.100"
      delegate_to: v-doorman
      register: keys
    - name: "Store v-node-1's SSH key"
      lineinfile:
        dest: ~/.ssh/known_hosts
        line: "{{ item }}"
      with_items: "{{ keys.stdout_lines }}"
    - name: "Get v-node-2's SSH key"
      command: "ssh-keyscan 10.20.30.101"
      delegate_to: v-doorman
      register: keys
    - name: "Store v-node-2's SSH key"
      lineinfile:
        dest: ~/.ssh/known_hosts
        line: "{{ item }}"
      with_items: "{{ keys.stdout_lines }}"
