# This bootstrap playbook's second play removes the user used for its first play.
# So, it's NOT idempotent, and so it must be run exactly once on a fresh install.
# We ensure that by MANUALLY adding the host in group 'bootstrapped' after this playbook.
- hosts: ubuntu:!bootstrapped
  become: yes
  gather_facts: no
  vars:
    ansible_user: "{{ bootstrap_user }}"
    ansible_ssh_pass: "{{ bootstrap_password }}"
    ansible_become_password: "{{ bootstrap_password }}"
  tasks:
    - name: Add user 'ansible'
      user:
        name: ansible
        append: yes
        groups:
          - sudo
          - users
        create_home: yes
        shell: /bin/bash
        comment: Ansible
    - name: Add SSH authorized key for user 'ansible'
      authorized_key:
        user: ansible
        exclusive: yes
        key: "{{ lookup('file', '../ssh/id_rsa.pub') }}"
    - name: Enable password-less sudo for user 'ansible'
      lineinfile:
        path: /etc/sudoers.d/010_ansible-nopasswd
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        create: yes
        mode: 0440
        validate: visudo -c -f %s
- hosts: ubuntu:!bootstrapped
  become: yes
  gather_facts: no
  tasks:
    - name: "Kill last processes of user '{{ bootstrap_user }}'"
      command: "killall --user {{ bootstrap_user }}"
    - name: "Remove user '{{ bootstrap_user }}'"
      user:
        name: "{{ bootstrap_user }}"
        state: absent
    - name: "Remove sudo configuration for user '{{ bootstrap_user }}'"
      file:
        path: "/etc/sudoers.d/010_{{ bootstrap_user }}-nopasswd"
        state: absent
    - name: "Remove home for user '{{ bootstrap_user }}'"
      file:
        path: "/home/{{ bootstrap_user }}"
        state: absent
