- hosts: home
  gather_facts: no
  tasks:
    - name: "Check SSH key is present"
      delegate_to: localhost
      lineinfile:
        path: ../ssh/known_hosts
        search_string: "{% if vars['networks']['home'] is defined %}{{ vars['networks']['home']['ip_address'] }}{% else %}{{ vars['networks']['v-internal']['ip_address'] }}{% endif %}"
        state: absent
      check_mode: yes
      register: check_result
      changed_when: no
    - block:
      - name: "Get SSH key"
        delegate_to: "{% if vars['networks']['home'] is defined %}localhost{% else %}v-doorman{% endif %}"
        command: "ssh-keyscan {% if vars['networks']['home'] is defined %}{{ vars['networks']['home']['ip_address'] }}{% else %}{{ vars['networks']['v-internal']['ip_address'] }}{% endif %}"
        register: keys
      - name: "Store SSH key"
        delegate_to: localhost
        lineinfile:
          path: ../ssh/known_hosts
          line: "{{ item }}"
        with_items: "{{ keys.stdout_lines }}"
      when: check_result.found == 0
