- hosts: ubuntu:&reachable
  become: yes
  gather_facts: no
  tasks:
    - name: Check last upgrade
      command: find /tmp -mtime -1 -name last-upgrade
      register: check_result
      changed_when: no
    - block:
      - name: Mark automatic packages
        command: apt-mark minimize-manual --yes
      - name: Upgrade packages
        apt:
          force_apt_get: yes
          update_cache: yes
          upgrade: dist
          purge: yes
          autoremove: yes
          autoclean: yes
      - name: Mark last upgrade
        command: touch /tmp/last-upgrade
      when: check_result.stdout == ''
