# Based on https://serverfault.com/a/1013036
- hosts: v-doorman:&ubuntu:&reachable
  become: yes
  gather_facts: no
  tasks:
    - name: Install tool to persist iptables
      apt:
        name:
          - iptables-persistent
        install_recommends: no
        state: present
    - name: Remove default netplan
      file:
        path: /etc/netplan/00-installer-config.yaml
        state: absent
      notify:
        - Apply netplan
    - name: Add custom netplan
      copy:
        dest: /etc/netplan/00-ansible-config.yaml
        content: |
          network:
            version: 2
            ethernets:
              {{ vars['networks']['home']['interface'] }}:
                dhcp4: true
                optional: false
              {{ vars['networks']['v-internal']['interface'] }}:
                dhcp4: false
                optional: true
                addresses:
                  - "{{ vars['networks']['v-internal']['ip_address'] }}/24"
      notify:
        - Apply netplan
    - name: Allow IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
    - name: Setup forwarding iptables (1/3)
      iptables:
        table: nat
        chain: POSTROUTING
        out_interface: "{{ vars['networks']['home']['interface'] }}"
        jump: MASQUERADE
      notify:
        - Persist iptables
    - name: Setup forwarding iptables (2/3)
      iptables:
        chain: FORWARD
        in_interface: "{{ vars['networks']['v-internal']['interface'] }}"
        out_interface: "{{ vars['networks']['home']['interface'] }}"
        jump: ACCEPT
      notify:
        - Persist iptables
    - name: Setup forwarding iptables (3/3)
      iptables:
        chain: FORWARD
        in_interface: "{{ vars['networks']['home']['interface'] }}"
        out_interface: "{{ vars['networks']['v-internal']['interface'] }}"
        jump: ACCEPT
      notify:
        - Persist iptables

  handlers:
    - name: Apply netplan
      command: netplan apply
    - name: Persist iptables
      command: netfilter-persistent save
