- hosts: pets
  become: yes
  tasks:
    # @todo Make this a loop over inventory
    - name: Add idee to known_hosts
      known_hosts:
        path: /etc/ssh/ssh_known_hosts
        name: idee.home.jacquev6.net
        key: "idee.home.jacquev6.net,192.168.1.52 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBN2pOBLyTwBBUtIR3mxNwo94vbvAmBmSGWPLvmk7wNTWWquhWLmSkhMGUBpgG2Hlos079qjaHDc7nCuQUW0WnhA="
    - name: Remove probe from known_hosts (@todo Apply task and remove it)
      known_hosts:
        path: /etc/ssh/ssh_known_hosts
        name: probe.home.jacquev6.net
        state: absent
    - name: Remove eeepc from known_hosts (@todo Apply task and remove it)
      known_hosts:
        path: /etc/ssh/ssh_known_hosts
        name: eeepc.home.jacquev6.net
        state: absent
    - name: Add nas2 to known_hosts
      known_hosts:
        path: /etc/ssh/ssh_known_hosts
        name: nas2.home.jacquev6.net
        key: "nas2.home.jacquev6.net,192.168.1.50 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBElrRuUiwpXhin+oBsfVUeLw4yRbvkahJCnZBp19XXa1Oq9ToskAWVr/dpC/RWZ6KqIBXjsRiUX6S8cnCioN2A0="
    - name: Remove butler from known_hosts (@todo Apply task and remove it)
      known_hosts:
        path: /etc/ssh/ssh_known_hosts
        name: butler.home.jacquev6.net
        state: absent
    - name: Remove media from known_hosts (@todo Apply task and remove it)
      known_hosts:
        path: /etc/ssh/ssh_known_hosts
        name: media.home.jacquev6.net
        state: absent
