- hosts: all
  become: yes
  tasks:
    # @todo Make this a loop over inventory
    - name: Add idee to known_hosts
      known_hosts:
        path: /etc/ssh/ssh_known_hosts
        name: idee.home.jacquev6.net
        key: "idee.home.jacquev6.net,192.168.1.52 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBN2pOBLyTwBBUtIR3mxNwo94vbvAmBmSGWPLvmk7wNTWWquhWLmSkhMGUBpgG2Hlos079qjaHDc7nCuQUW0WnhA="
    - name: Add doorman to known_hosts
      known_hosts:
        path: /etc/ssh/ssh_known_hosts
        name: doorman.home.jacquev6.net
        key: "doorman.home.jacquev6.net,192.168.1.51 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBONA/+RKU5Ax101KoQCELPJT/fT9zuA/g4j+ArlieitJO06l68PWqS6GIS8uoM7cCnSeX8ot+Oq97W0aO+20Oyo="
    - name: Add probe to known_hosts
      known_hosts:
        path: /etc/ssh/ssh_known_hosts
        name: probe.home.jacquev6.net
        key: "probe.home.jacquev6.net,192.168.1.69 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEc0IbUXrMNlN3PVLveLSPJOD3oeAWUA+Tgboe9QQkLyrU4Nrb2GI1uqRqZDLF17K9i1lojR6v1CsP2u2RIIFKg="
    - name: Add eeepc to known_hosts
      known_hosts:
        path: /etc/ssh/ssh_known_hosts
        name: eeepc.home.jacquev6.net
        key: "eeepc.home.jacquev6.net,192.168.1.67 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMJ+nR/4r1xL12HW+mp9E+FVyqIymRvuNC8MPyDhXBmx1QRdmcxifHX6BYZnAhyRO+/4a+SYYUKm9kWYk/+rxq0="
    - name: Add nas2 to known_hosts
      known_hosts:
        path: /etc/ssh/ssh_known_hosts
        name: nas2.home.jacquev6.net
        key: "nas2.home.jacquev6.net,192.168.1.50 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBElrRuUiwpXhin+oBsfVUeLw4yRbvkahJCnZBp19XXa1Oq9ToskAWVr/dpC/RWZ6KqIBXjsRiUX6S8cnCioN2A0="
