- hosts: ubuntu
  become: yes
  gather_facts: no
  tasks:
    - name: Ensure config directory exists
      file:
        path: /etc/systemd/resolved.conf.d
        state: directory
    - name: Set DNS suffix (allow `ping name` instead of `ping name.home.jacquev6.net`)
      copy:
        dest: /etc/systemd/resolved.conf.d/00-home.jacquev6.net.conf
        content: |
          [Resolve]
          Domains=home.jacquev6.net
      notify: reload systemd-resolved
    # Not investigated deeply: enabling IPv6 seems to break DNS resolution after a while.
    # Based on https://support.purevpn.com/how-to-disable-ipv6-linuxubuntu
    - name: Disable IPv6 - all
      sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: '1'
        reload: yes
    - name: Disable IPv6 - default
      sysctl:
        name: net.ipv6.conf.default.disable_ipv6
        value: '1'
        reload: yes
    - name: Disable IPv6 - lo
      sysctl:
        name: net.ipv6.conf.lo.disable_ipv6
        value: '1'
        reload: yes
    - name: Disable IPv6 - eth0
      sysctl:
        name: net.ipv6.conf.eth0.disable_ipv6
        value: '1'
        reload: yes
  handlers:
    - name: reload systemd-resolved
      systemd:
        daemon_reload: yes
        name: systemd-resolved
        state: restarted
