- hosts: pc:&gpu:&ubuntu
  become: yes
  gather_facts: no
  tasks:
    - name: Install NVidia drivers and utilities
      apt:
        name:
          - nvidia-headless-460
          - nvidia-utils-460
        install_recommends: no
        state: latest

- hosts: ubuntu
  become: yes
  gather_facts: no
  tasks:
    - name: Install file system packages
      apt:
        name:
          - bindfs
          - cifs-utils
          - exfat-fuse
        state: present
    - name: Add nas2 credentials
      copy:
        src: nas2.secret.credentials
        dest: /etc/nas2_credentials
        mode: u=r,g=,o=
    - name: Mount nas2 (vincent)
      mount:
        src: //nas2.home.jacquev6.net/vincent
        fstype: cifs
        opts: credentials=/etc/nas2_credentials,vers=2.0,uid=0,gid=0
        path: /mnt/nas2/vincent
        state: mounted
    - name: Mount nas2 (vincent-no-backup)
      mount:
        src: //nas2.home.jacquev6.net/vincent-no-backup
        fstype: cifs
        opts: credentials=/etc/nas2_credentials,vers=2.0,uid=0,gid=0
        path: /mnt/nas2/vincent-no-backup
        state: mounted
