- hosts: docker
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name:
          - docker.io
          - python3-docker
          - docker-compose
        state: present
    - name: Add user 'jacquev6' to group 'docker'
      user:
        name: jacquev6
        groups:
          - docker
        append: true
    - name: Start Docker on boot
      # https://bugs.launchpad.net/ubuntu/+source/docker/+bug/1858441
      systemd:
        name: docker
        enabled: yes
        state: started
