- hosts: ubuntu
  become: yes
  gather_facts: no
  tasks:
    - name: Add user 'jacquev6'
      user:
        name: jacquev6
        create_home: yes
        shell: /bin/bash
        comment: Vincent Jacques
        # At least one user must have a password, to rescue the system if it fails before starting sshd
        # Plain-text password: see note "jacquev6 local password" in LastPass
        # Encrypted using https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module
        password: $6$vKWPUcs2g3t0$GMm2VzQl7eJd1ywChkqSF9kNkPcox/15ZwSyGnAgm.5ZA3xQFAcUWu/DDqezMxmxTAXl1Z44E9KgZ9uFOL8ns/
    - name: Add SSH authorized key for user 'jacquev6'
      authorized_key:
        user: jacquev6
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDO5LxWssyK3ZqlBkYOPZhZseUlsL7ebp68x9SA/KR91afkW4sFVVcVzmlVDui4Js/YrYlUd14cGZ311oXqKIDT1x09MSfST6fO5+LCJbTTNl0pmZq/i11OsBJSOcmWq2mHBh0YRV/DWnpoJ/+cjOODLn0sTuo8VEM5ryxVsDs315JRKkrUwOsmDDW/Hu9mf6QccnUqLx518h8eSU+NHlaCk+cIfxDySwacIXZSOLSbK4q9nUSbG98T+85IWPUM7r3QwMVYmfLFBtX0DA+AMA6DBZkXW6eFaRujEP6B6mYkW8Q+6oyx6uNX6e6YS5u3nF2emiO+eR88Th42M9LFby+n jacquev6"
    - name: Enable password-less sudo for user 'jacquev6'
      lineinfile:
        path: /etc/sudoers.d/010_jacquev6-nopasswd
        line: 'jacquev6 ALL=(ALL) NOPASSWD: ALL'
        create: yes
        mode: 0440
        validate: visudo -c -f %s
