- hosts: pets
  become: yes
  tasks:
    - name: Add user 'butler'
      user:
        name: butler
        create_home: yes
        shell: /bin/bash
        comment: Vincent Jacques
    - name: Add SSH authorized key for user 'butler'
      authorized_key:
        user: butler
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUwSPGbtQtNTW1pHVKiYDOWfHy+eeZuy5Wbiha0nLKew6k9hOKxRbWf54xb72p+X9LSvyDHrRMnt2Spy35Jx2ZWKnvLQul7pphiR0GOpgH2CFBenPs5Y/G7puTz3mRkAGxH8JldZYxnx2MHpN66tCxLvPUnokWVmrXUxF0MLRXkv22/yEKlzysWP9+5u6sUP8eZ59ogetXu3LdR6wuvbdAr8g7+cAG+kHH0sW1J/sHzcvAPOh7Tv7Ev67gJ1dE7lMQzhDpK/dRYFjZkqHoHq2SFREP36gNtFM+NmQR4cSlJ806qNpNvRmMe61kf9YmVEPOWSnV9CIx7xB73DHE/mpR butler"
