- hosts: pi:&ubuntu:&gluster
  become: yes
  gather_facts: no
  tasks:
    # - name: Mount Gluster brick
    #   mount:
    #     src: PARTUUID={{ large_gluster_brick }}
    #     fstype: xfs
    #     path: /gluster/bricks/large-1
    #     state: mounted
    - name: Install Gluster
      apt:
        name:
          - glusterfs-server
        state: present
    - name: Start Gluster
      systemd:
        name: glusterd
        enabled: yes
        state: started
    - name: Unify the Gluster cluster
      gluster.gluster.gluster_peer:
        state: present
        nodes:
          - 192.168.1.102  # pi4b4-3
          - 192.168.1.103  # pi4b4-4
      run_once: true
