- hosts:
    - butler
    - idee
  become: yes
  tasks:
    - name: Install 'cifs-utils' package
      apt:
        name: cifs-utils
        state: present
    - name: Add nas2 credentials
      copy:
        src: nas2.secret.credentials
        dest: /etc/nas2_credentials
        mode: u=r,g=,o=
- hosts:
    - butler
  become: yes
  tasks:
    # @todo Mount whole drive like on idee, and re-mount DockerRegistry in ~/Data/Hacking using bindfs
    - name: Mount nas2/vincent/HackingData/DockerRegistry
      mount:
        path: /media/DockerRegistry
        src: //nas2.home.jacquev6.net/vincent/HackingData/DockerRegistry
        fstype: cifs
        opts: credentials=/etc/nas2_credentials,vers=2.0,uid=0,gid=0
        state: mounted
- hosts:
    - idee
  become: yes
  tasks:
    - name: Mount nas2/vincent
      mount:
        path: /media/nas2
        src: //nas2.home.jacquev6.net/vincent
        fstype: cifs
        opts: credentials=/etc/nas2_credentials,vers=2.0,uid=0,gid=0
        state: mounted
