- hosts: butler
  become: yes
  tasks:
    - name: Install exfat
      apt:
        name:
          - exfat-fuse
        state: latest
    - name: Mount Black
      mount:
        path: /media/Black
        src: /dev/sda2
        fstype: exfat
        state: mounted
