- hosts: media
  become: yes
  tasks:
    # @todo (when Big is available) Homogenize with butler:
    # - remove these three mounts
    # - bindfs from /mnt/big
    - name: Mount Media
      mount:
        src: /dev/sda2
        fstype: ntfs
        opts: nofail
        path: /media/Media
        state: mounted
    - name: Mount MongoDB data with appropriate uid:gid
      mount:
        src: /media/Media/MyMediaGathering/.mongo
        fstype: fuse.bindfs
        # mongodb user's id in mongo image
        opts: force-user=999,force-group=999
        path: /home/jacquev6/Data/Hacking/MyMediaGatherer/MongoDB
        state: mounted
    - name: Mount Gathering data at appropriate location
      mount:
        src: /media/Media/MyMediaGathering
        fstype: fuse.bindfs
        path: /home/jacquev6/Data/Hacking/MyMediaGatherer/Gathering
        state: mounted
- hosts: butler
  become: yes
  tasks:
    - name: Mount MongoDB data with appropriate uid:gid
      mount:
        src: /mnt/black/my-media-gathering/.mongo
        fstype: fuse.bindfs
        # mongodb user's id in mongo image
        opts: force-user=999,force-group=999
        path: /home/jacquev6/Data/Hacking/MyMediaGatherer/MongoDB
        state: mounted
    - name: Mount Gathering data at appropriate location
      mount:
        src: /mnt/black/my-media-gathering
        fstype: fuse.bindfs
        path: /home/jacquev6/Data/Hacking/MyMediaGatherer/Gathering
        state: mounted
- hosts:
    - media
    - butler
  become: yes
  tasks:
    - name: Copy NGinx configuration file
      copy:
        src: my-media-gatherer.nginx.conf
        dest: /home/jacquev6/Data/Hacking/MyMediaGatherer/nginx.conf
    - name: Run My Media Gatherer
      docker_compose:
        state: present
        project_name: my-media-gatherer
        pull: yes
        remove_orphans: yes
        definition:
          version: "3.7"
          services:
            redis:
              image: redis:alpine
              restart: always
            mongo:
              image: mongo:4.2.6
              restart: always
              volumes:
                - /home/jacquev6/Data/Hacking/MyMediaGatherer/MongoDB:/data/db
            graphql-api:
              image: registry.jacquev6.net/my-media-gatherer/graphql-api:latest
              restart: always
              volumes:
                - /home/jacquev6/Data/Hacking/MyMediaGatherer/Gathering:/gathering
              working_dir: /my-media-gatherer/graphql-api
              environment:
                FLASK_RUN_HOST: "0.0.0.0"
                MMG_GATHERING_PATH: /gathering
                MMG_REDIS_HOST: redis
                MMG_MONGO_HOST: mongo
                MMG_MONGO_COLLECTION: my_video_collection  # @todo Rename the DB
              depends_on:
                - redis
                - mongo
              command:
                - flask
                - run
            rq-worker:
              image: registry.jacquev6.net/my-media-gatherer/graphql-api:latest
              init: true
              restart: always
              volumes:
                - /home/jacquev6/Data/Hacking/MyMediaGatherer/Gathering:/gathering
              working_dir: /my-media-gatherer/graphql-api
              environment:
                MMG_GATHERING_PATH: /gathering
                MMG_MONGO_HOST: mongo
                MMG_MONGO_COLLECTION: my_video_collection  # @todo Rename the DB
              depends_on:
                - redis
                - mongo
              command:
                - rq
                - worker
                - --url
                - redis://redis
            website:
              image: registry.jacquev6.net/my-media-gatherer/website:latest
              restart: always
            nginx:
              image: nginx
              restart: always
              volumes:
                - /home/jacquev6/Data/Hacking/MyMediaGatherer/nginx.conf:/etc/nginx/nginx.conf
              depends_on:
                - graphql-api
                - website
              ports:
                - "8080:80"
