- hosts: idee
  become: yes
  tasks:
    - name: Mount Ripping data at appropriate location
      mount:
        src: /mnt/data1/ChainRip
        fstype: fuse.bindfs
        path: /home/jacquev6/Data/Hacking/MediaUtils/ChainRip
        state: mounted
    - name: Mount output directory at appropriate location
      mount:
        # Short term location, directly on Big, temporarilly plugged in Idee
        src: /mnt/big/IncomingDvdImages
        # Long term location, when we rip new DVDs one by one
        # (Media will fetch them from the nas)
        # src: /mnt/nas2/Media/IncomingDvdImages
        fstype: fuse.bindfs
        path: /home/jacquev6/Data/Hacking/MediaUtils/ChainRip/checked
        state: mounted
    - include_vars:
        file: smtp_url.secret.yml
    - name: Run Media Utils
      docker_compose:
        state: present
        project_name: media-utils
        remove_orphans: yes
        definition:
          version: "2.4"
          services:
            redis:
              image: redis:alpine
            chain-rip:
              init: true
              depends_on:
                - redis
              image: registry.jacquev6.net/media-utils/main:20200809-104042  # media-utils-version
              environment:
                - MEDIA_UTILS_REDIS_URL=redis://redis
                - MEDIA_UTILS_SMTP_URL={{ smtp_url }}
              volumes:
                - /home/jacquev6/Data/Hacking/MediaUtils/ChainRip:/data
              devices:
                - /dev/sr1
                - /dev/sr2
              command:
                - chain-rip
                - --mail-to
                - jacquev6@gmail.com
                - /dev/sr1
                - /dev/sr2
                - /data
            rqmonitor:
              init: true
              depends_on:
                - redis
              image: pranavgupta1234/rqmonitor
              environment:
                - RQ_MONITOR_REDIS_URL=redis://redis
              ports:
                - 8899:8899
            rq-dashboard:
              init: true
              depends_on:
                - redis
              image: eoranged/rq-dashboard
              environment:
                - RQ_DASHBOARD_REDIS_URL=redis://redis
              ports:
                - 9181:9181
            rip-dvd-worker:
              init: true
              scale: 2
              depends_on:
                - redis
              image: registry.jacquev6.net/media-utils/workers/rip-dvd:20200809-104042  # media-utils-version
              environment:
                - RQ_REDIS_URL=redis://redis
              volumes:
                - /home/jacquev6/Data/Hacking/MediaUtils/ChainRip:/data
              privileged: true  # For `eject`
            check-iso-worker:
              init: true
              depends_on:
                - redis
              image: registry.jacquev6.net/media-utils/workers/check-iso:20200809-104042  # media-utils-version
              environment:
                - RQ_REDIS_URL=redis://redis
              volumes:
                - /home/jacquev6/Data/Hacking/MediaUtils/ChainRip:/data
