- hosts: idee
  become: yes
  tasks:
    - name: Run Media Utils
      docker_compose:
        state: present
        project_name: media-utils
        pull: yes
        remove_orphans: yes
        definition:
          version: "3.6"
          services:
            chain-rip:
              image: registry.jacquev6.net/media-utils/main:20200808-100910  # media-utils-version
              environment:
                - MEDIA_UTILS_REDIS_URL=redis://redis
              devices:
                - /dev/sr1
                - /dev/sr2
              command:
                - chain-rip
                - /dev/sr1
                - /dev/sr2
            redis:
              image: redis:alpine
              restart: always
            rip-dvd-worker:
              image: registry.jacquev6.net/media-utils/workers/rip-dvd:20200808-100910  # media-utils-version
              environment:
                - RQ_REDIS_URL=redis://redis
              devices:
                - /dev/sr1
                - /dev/sr2
        scale:
          rip-dvd-worker: 2
