user nginx;
worker_processes 1;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  log_format main '$remote_addr - $remote_user [$time_local] $host "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';
  access_log /var/log/nginx/access.log main;

  sendfile on;

  keepalive_timeout 65;

  server_names_hash_bucket_size 64;  # For long server names (http://nginx.org/en/docs/http/server_names.html)

  server {
    server_name registry.jacquev6.net;
    listen 443 ssl;
    ssl_certificate /etc/nginx/registry.jacquev6.net.crt;
    ssl_certificate_key /etc/nginx/registry.jacquev6.net.key;

    # https://docs.docker.com/registry/recipes/nginx/
    client_max_body_size 0;
    chunked_transfer_encoding on;

    location / {
      proxy_pass http://docker_registry:5000/;

      # https://docs.docker.com/registry/recipes/nginx/
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
