user nginx;
worker_processes 1;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  log_format main '$remote_addr - $remote_user [$time_local] $host "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';
  access_log /var/log/nginx/access.log main;

  sendfile on;

  keepalive_timeout 65;

  server_names_hash_bucket_size 64;  # For long server names (http://nginx.org/en/docs/http/server_names.html)

  server {
    server_name home.jacquev6.net;
    listen 443 ssl;
    ssl_certificate /etc/nginx/home.jacquev6.net.crt;
    ssl_certificate_key /etc/nginx/home.jacquev6.net.key;

    location / {
      proxy_pass http://always_200/;
    }
  }

  server {
    server_name dyn.vincent-jacques.net;
    listen 443 ssl;
    ssl_certificate /etc/nginx/dyn.vincent-jacques.net.crt;
    ssl_certificate_key /etc/nginx/dyn.vincent-jacques.net.key;

    location /turkshead {
      proxy_pass http://draw_turks_head_demo/;
    }
  }

  server {
    server_name www.vincent-jacques.net;
    listen 443 ssl;
    ssl_certificate /etc/nginx/www.vincent-jacques.net.crt;
    ssl_certificate_key /etc/nginx/www.vincent-jacques.net.key;

    return 301 https://vincent-jacques.net$request_uri;
  }
}
