apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.baseName }}-admin
spec:
  selector:
    matchLabels:
      app: {{ .Values.baseName }}-admin
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.baseName }}-admin
    spec:
      containers:
        - name: {{ .Values.baseName }}-admin
          image: jacquev6/splight:{{ .Values.version }}.admin-frontend
          ports:
            - containerPort: 80
          env:
            - name: SPLIGHT_API_URL
              value: "{{ .Values.apiPublicUrl }}"
          resources:
            requests:
              cpu: 10m
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.baseName }}-admin
spec:
  type: NodePort
  selector:
    app: {{ .Values.baseName }}-admin
  ports:
    - port: 80
