apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
spec:
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: docker-registry
          image: registry:2.7
          volumeMounts:
            - name: docker-registry
              mountPath: /var/lib/registry
      volumes:
        - name: docker-registry
          hostPath:
            path: /mnt/nas2/HackingData/DockerRegistry
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
spec:
  type: ClusterIP
  selector:
    app: docker-registry
  ports:
    - port: 5000
# @todo Add a CronJob to run the registry's garbage collector
# (Stop the world beforehand: https://docs.docker.com/registry/garbage-collection/#more-details-about-garbage-collection)
