apiVersion: apps/v1
kind: Deployment
metadata:
  name: draw-turks-head-demo
spec:
  selector:
    matchLabels:
      app: draw-turks-head-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: draw-turks-head-demo
    spec:
      containers:
        - name: draw-turks-head-demo
          image: docker.jacquev6.net/draw-turks-head-demo:20210416-135136
      # @todo Make this secret global: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account
      imagePullSecrets:
        - name: docker-registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: draw-turks-head-demo
spec:
  type: ClusterIP
  selector:
    app: draw-turks-head-demo
  ports:
    - port: 80
