apiVersion: v1
kind: ConfigMap
metadata:
  name: public-fanout-conf
data:
  dyn.vincent-jacques.net.conf: |
    server {
      listen 443 ssl;
      server_name dyn.vincent-jacques.net;

      ssl_certificate /etc/letsencrypt/live/dyn.vincent-jacques.net/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/dyn.vincent-jacques.net/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/dyn.vincent-jacques.net/chain.pem;
      ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

      location /turkshead {
        proxy_pass http://draw-turks-head-demo:80/;
      }
    }
  home.jacquev6.net.conf: |
    server {
      listen 443 ssl;
      server_name home.jacquev6.net;

      ssl_certificate /etc/letsencrypt/live/home.jacquev6.net/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/home.jacquev6.net/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/home.jacquev6.net/chain.pem;

      return 200 'OK';
    }
  docker.jacquev6.net.conf: |
    server {
      listen 443 ssl;
      server_name docker.jacquev6.net;

      ssl_certificate /etc/letsencrypt/live/docker.jacquev6.net/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/docker.jacquev6.net/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/docker.jacquev6.net/chain.pem;
      ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

      # https://docs.docker.com/registry/recipes/nginx/
      client_max_body_size 0;
      chunked_transfer_encoding on;

      # https://serverfault.com/questions/768693/nginx-how-to-completely-disable-request-body-buffering
      proxy_http_version 1.1;
      proxy_request_buffering off;

      location / {
        proxy_pass http://docker-registry:5000/;

        # https://docs.docker.com/registry/recipes/nginx/
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
  www.jacquev6.net.conf: |
    server {
      listen 443 ssl;
      server_name www.jacquev6.net;

      ssl_certificate /etc/letsencrypt/live/www.jacquev6.net/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/www.jacquev6.net/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/www.jacquev6.net/chain.pem;

      return 301 https://jacquev6.net$request_uri;
    }
  www.vincent-jacques.net.conf: |
    server {
      listen 443 ssl;
      server_name www.vincent-jacques.net;

      ssl_certificate /etc/letsencrypt/live/www.vincent-jacques.net/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/www.vincent-jacques.net/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/www.vincent-jacques.net/chain.pem;

      return 301 https://vincent-jacques.net$request_uri;
    }
  www.etcavole.fr.conf: |
    server {
      listen 443 ssl;
      server_name www.etcavole.fr;

      ssl_certificate /etc/letsencrypt/live/www.etcavole.fr/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/www.etcavole.fr/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/www.etcavole.fr/chain.pem;

      return 301 https://etcavole.fr$request_uri;
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: public-fanout-entrypoint
data:
  50-copy-conf.sh: |
    cp /etc/nginx/conf.d.ro/* /etc/nginx/conf.d/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-fanout
spec:
  replicas: 1
  strategy:  # Avoid a dead lock with the hostPorts
    type: Recreate
  selector:
    matchLabels:
      app: public-fanout
  template:
    metadata:
      labels:
        app: public-fanout
    spec:
      # Schedule only on the node targeted by the various domains served by this fanout
      nodeName: pi4b4-1
      containers:
        - name: public-fanout
          image: jonasal/nginx-certbot:1.2.0-nginx1.19.9
          ports:
            - containerPort: 80
              hostPort: 10080
            - containerPort: 443
              hostPort: 10443
          env:
            - name: CERTBOT_EMAIL
              value: letsencrypt.org@vincent-jacques.net
          volumeMounts:
            - name: public-fanout-conf
              mountPath: /etc/nginx/conf.d.ro/
            - name: public-fanout-entrypoint
              mountPath: /docker-entrypoint.d/50-copy-conf.sh
              subPath: 50-copy-conf.sh
            - name: public-fanout-nginx-secrets
              mountPath: /etc/letsencrypt
      volumes:
        - name: public-fanout-conf
          configMap:
            name: public-fanout-conf
        - name: public-fanout-entrypoint
          configMap:
            name: public-fanout-entrypoint
            defaultMode: 0755
        - name: public-fanout-nginx-secrets
          hostPath:
            path: /hacking_data/nginx_secrets
            type: DirectoryOrCreate
