apiVersion: v1
kind: Endpoints
metadata:
  name: gluster
subsets:
- addresses:
    - ip: 192.168.1.100
  ports:
    - port: 1
- addresses:
    - ip: 192.168.1.101
  ports:
    - port: 1
- addresses:
    - ip: 192.168.1.102
  ports:
    - port: 1
- addresses:
    - ip: 192.168.1.103
  ports:
    - port: 1
---
apiVersion: v1
kind: Service
metadata:
  name: gluster
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: Pod
metadata:
  name: glusterfs
spec:
  containers:
    - name: glusterfs
      image: nginx
      volumeMounts:
      - mountPath: "/mnt/test-1"
        name: test-1
  volumes:
    - name: test-1
      glusterfs:
        endpoints: gluster
        path: test-1
