all:
  children:
    # @todo (when group "legacy" is empty): remove groups "legacy" and "modern"
    legacy:
      hosts:
        # @todo Install butler, migrate doorman's duties to butler, decommission doorman
        doorman.home.jacquev6.net:
          # Headless Raspberry Pi 2
          # Main entry point from WAN (using port forwarding)
          # Always on, monitored by Uptime Robot
        # @todo Migrate idee to group "modern"
        idee.home.jacquev6.net:
          # Headless AMD64 with a big GPU
      vars:
        ansible_user: jacquev6
    modern:
      hosts:
        probe.home.jacquev6.net:
          # Raspberry Pi 3 model B
          # OS: Raspbian
          # Read-only /boot and overlayfs on / (using raspi-config's "Advanced" menu)
        eeepc.home.jacquev6.net:
          # Old eeePC laptop
          # OS: Ubuntu (minimal)
          # overlayfs on / (using Ubuntu's overlayroot package)
      vars:
        ansible_user: ansible
        ansible_ssh_private_key_file: ansible.id_rsa
  vars:
    ansible_python_interpreter: /usr/bin/python3
