all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ansible
    ansible_ssh_private_key_file: ansible.id_rsa

  children:

    # Groups with one machines used as convenient short aliases
    pets:
      children:
        butler:
          hosts:
            butler.home.jacquev6.net:
              # Headless Raspberry Pi 4 model B with 4GB of RAM
              # Main entry point from WAN (using port forwarding)
              # Always on, monitored by Uptime Robot
        idee:
          hosts:
            idee.home.jacquev6.net:
              # Headless AMD64 with a big GPU
        teuse:
          hosts:
            teuse.home.jacquev6.net:
              # VirtualBox
    cattle:
      children:
        pi4b4:
          # Headless Raspberry Pis 4 model B with 4GB of RAM
          children:
            pi4b4_1:
              hosts:
                pi4b4-1.home.jacquev6.net:
            pi4b4_2:
              hosts:
                pi4b4-2.home.jacquev6.net:
            pi4b4_3:
              hosts:
                pi4b4-3.home.jacquev6.net:

    # Groups used as tags to decide which machines get which playbooks
    ## hardware
    pi:
      children:
        butler:
        pi4b4:

    pc:
      children:
        idee:
        teuse:

    gpu:
      children:
        idee:

    ## Operating system
    ubuntu:
      children:
        butler:
        idee:
        media:
        teuse:
        pi4b4:
      vars:
        bootstrap_user: ubuntu
        bootstrap_password: ubuntu

    ## Software
    containers:
      children:
        docker:
          children:
            butler:
            media:
            idee:
        kubernetes:
          children:
            cattle:
