all:
  vars:
    ansible_user: ansible

  hosts:
    v-doorman:
    v-node-1:
    v-node-2:

  children:
    # By OS
    ubuntu:
      hosts:
        v-doorman:
        v-node-1:
        v-node-2:
      vars:
        bootstrap_user: ubuntu
        bootstrap_password: ubuntu
